name: login_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^0.2.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  animated_bottom_navigation_bar: ^0.1.2+2
  circular_reveal_animation: ^1.1.5
  flutter_svg: 0.18.0
  flutter_swiper: ^1.1.6
  geolocator: ^3.0.1
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0
  flutter_launcher_icons: ^0.8.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  shared_preferences: ^0.5.12+4
  flare_splash_screen: ^3.0.1
  bubble: ^1.1.9+1
  flutter_dialogflow: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/verdant.jpg"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/

  fonts:
    - family: LeonSans
      fonts:
        - asset: fonts/LeonSans-Regular.otf
          weight: 400
        - asset: fonts/LeonSans-Medium.otf
          weight: 500
        - asset: fonts/LeonSans-Bold.otf
          weight: 700
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
    - family: Sigmar
      fonts:
        - asset: fonts/SigmarOne-Regular.ttf


